language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

notifications:
  on_success: never
  on_failure: always
  email: false

branches:
  only:
    - master

matrix:
  fast_finish: true

before_install:
  - composer self-update

before_script:
  - composer install --dev --no-interaction --optimize-autoloader
  - mkdir -p log/phpunit

script:
  - ./vendor/bin/phpunit --configuration phpunit.xml --coverage-clover log/phpunit/clover.xml test/

#after_script:
#  - php vendor/bin/coveralls -v
